In [2]:
import pandas as pd
import numpy as np

In [3]:
# loading datasets
campaigns = pd.read_csv('datasets/campaigns.csv')
customers = pd.read_csv('datasets/customers.csv')
events = pd.read_csv('datasets/events.csv')
products = pd.read_csv('datasets/products.csv')
transactions = pd.read_csv('datasets/transactions.csv')

In [4]:
# cleaning datasets
datasets = {
    "campaigns": campaigns,
    "customers": customers,
    "events": events,
    "products": products,
    "transactions": transactions
}

for name, df in datasets.items():
    print(f"The shape of {name} dataset is {df.shape}")
    print(f"The missing values in {name} dataset is {df.isna().sum()}")
    print(f"The duplicate values in {name} is {df.duplicated().sum()}")
    print()

print("The Missing values are in EVENTS and TRANSACTIONS dataset ")

The shape of campaigns dataset is (50, 7)
The missing values in campaigns dataset is campaign_id        0
channel            0
objective          0
start_date         0
end_date           0
target_segment     0
expected_uplift    0
dtype: int64
The duplicate values in campaigns is 0

The shape of customers dataset is (100000, 7)
The missing values in customers dataset is customer_id            0
signup_date            0
country                0
age                    0
gender                 0
loyalty_tier           0
acquisition_channel    0
dtype: int64
The duplicate values in customers is 0

The shape of events dataset is (2000000, 12)
The missing values in events dataset is event_id                     0
timestamp                    0
customer_id                  0
session_id                   0
event_type                   0
product_id              200371
device_type              40300
traffic_source               0
campaign_id                  0
page_category                0
session_duration_sec         0
experiment_group             0
dtype: int64
The duplicate values in events is 0

The shape of products dataset is (2000, 6)
The missing values in products dataset is product_id     0
category       0
brand          0
base_price     0
launch_date    0
is_premium     0
dtype: int64
The duplicate values in products is 0

The shape of transactions dataset is (103127, 9)
The missing values in transactions dataset is transaction_id          0
timestamp               0
customer_id             0
product_id          10449
quantity                0
discount_applied        0
gross_revenue       10449
campaign_id             0
refund_flag             0
dtype: int64
The duplicate values in transactions is 0

The Missing values are in EVENTS and TRANSACTIONS dataset

In [5]:
# cleaning missing values from events
print((events.isna().sum())/len(events) * 100)

event_id                 0.00000
timestamp                0.00000
customer_id              0.00000
session_id               0.00000
event_type               0.00000
product_id              10.01855
device_type              2.01500
traffic_source           0.00000
campaign_id              0.00000
page_category            0.00000
session_duration_sec     0.00000
experiment_group         0.00000
dtype: float64

In [6]:
events.dropna(inplace=True)

In [7]:
events.shape

(1763374, 12)

In [8]:
# cleaning missing values from Transactions
print((transactions.isna().sum()/len(transactions)) * 100)

transaction_id       0.000000
timestamp            0.000000
customer_id          0.000000
product_id          10.132167
quantity             0.000000
discount_applied     0.000000
gross_revenue       10.132167
campaign_id          0.000000
refund_flag          0.000000
dtype: float64

In [9]:
transactions.dropna(inplace=True)

In [10]:
transactions.shape

(92678, 9)

In [11]:
datasets = {
    "campaigns": campaigns,
    "customers": customers,
    "events": events,
    "products": products,
    "transactions": transactions
}

for name, df in datasets.items():
    print(f"The info of {name} dataset is {df.info()}")
    print()

print("The Product_id from EVENTS, TRANSACTIONS is Float")

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   campaign_id      50 non-null     int64
 1   channel          50 non-null     str
 2   objective        50 non-null     str
 3   start_date       50 non-null     str
 4   end_date         50 non-null     str
 5   target_segment   50 non-null     str
 6   expected_uplift  50 non-null     float64
dtypes: float64(1), int64(1), str(5)
memory usage: 5.2 KB
The info of campaigns dataset is None

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          100000 non-null  int64
 1   signup_date          100000 non-null  str
 2   country              100000 non-null  str
 3   age                  100000 non-null  int64
 4   gender               100000 non-null  str
 5   loyalty_tier         100000 non-null  str
 6   acquisition_channel  100000 non-null  str
dtypes: int64(2), str(5)
memory usage: 8.3 MB
The info of customers dataset is None

<class 'pandas.DataFrame'>
Index: 1763374 entries, 0 to 1999999
Data columns (total 12 columns):
 #   Column                Dtype
---  ------                -----
 0   event_id              int64
 1   timestamp             str
 2   customer_id           int64
 3   session_id            int64
 4   event_type            str
 5   product_id            float64
 6   device_type           str
 7   traffic_source        str
 8   campaign_id           int64
 9   page_category         str
 10  session_duration_sec  float64
 11  experiment_group      str
dtypes: float64(2), int64(4), str(6)
memory usage: 259.8 MB
The info of events dataset is None

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product_id   2000 non-null   int64
 1   category     2000 non-null   str
 2   brand        2000 non-null   str
 3   base_price   2000 non-null   float64
 4   launch_date  2000 non-null   str
 5   is_premium   2000 non-null   int64
dtypes: float64(1), int64(2), str(3)
memory usage: 142.7 KB
The info of products dataset is None

<class 'pandas.DataFrame'>
Index: 92678 entries, 0 to 103126
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    92678 non-null  int64
 1   timestamp         92678 non-null  str
 2   customer_id       92678 non-null  int64
 3   product_id        92678 non-null  float64
 4   quantity          92678 non-null  int64
 5   discount_applied  92678 non-null  float64
 6   gross_revenue     92678 non-null  float64
 7   campaign_id       92678 non-null  int64
 8   refund_flag       92678 non-null  int64
dtypes: float64(3), int64(5), str(1)
memory usage: 8.8 MB
The info of transactions dataset is None

The Product_id from EVENTS, TRANSACTIONS is Float

In [12]:
events['product_id'] = events['product_id'].astype('Int64')
transactions['product_id'] = transactions['product_id'].astype('Int64')

In [13]:
events.info()

<class 'pandas.DataFrame'>
Index: 1763374 entries, 0 to 1999999
Data columns (total 12 columns):
 #   Column                Dtype
---  ------                -----
 0   event_id              int64
 1   timestamp             str
 2   customer_id           int64
 3   session_id            int64
 4   event_type            str
 5   product_id            Int64
 6   device_type           str
 7   traffic_source        str
 8   campaign_id           int64
 9   page_category         str
 10  session_duration_sec  float64
 11  experiment_group      str
dtypes: Int64(1), float64(1), int64(4), str(6)
memory usage: 261.5 MB

In [14]:
transactions.info()

<class 'pandas.DataFrame'>
Index: 92678 entries, 0 to 103126
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    92678 non-null  int64
 1   timestamp         92678 non-null  str
 2   customer_id       92678 non-null  int64
 3   product_id        92678 non-null  Int64
 4   quantity          92678 non-null  int64
 5   discount_applied  92678 non-null  float64
 6   gross_revenue     92678 non-null  float64
 7   campaign_id       92678 non-null  int64
 8   refund_flag       92678 non-null  int64
dtypes: Int64(1), float64(2), int64(5), str(1)
memory usage: 8.8 MB

In [15]:
events.to_csv('cleaned_events.csv', index=False)

In [16]:
transactions.to_csv('cleaned_transact.csv', index=True)

In [17]:
campaigns.head()

,campaign_id,channel,objective,start_date,end_date,target_segment,expected_uplift
0,1,Paid Search,Cross-sell,2021-10-25,2021-11-26,Deal Seekers,0.022
1,2,Email,Retention,2021-10-24,2021-12-24,Deal Seekers,0.116
2,3,Email,Reactivation,2023-10-08,2023-11-30,Churn Risk,0.100
3,4,Display,Reactivation,2022-07-25,2022-10-07,Deal Seekers,0.111
4,5,Social,Acquisition,2022-07-09,2022-09-29,New Customers,0.144

In [18]:
products.head()

   product_id     category     brand  base_price launch_date  is_premium
0           1      Grocery  Brand_58       14.19  2021-08-02           0
1           2      Fashion   Brand_1       25.80  2021-09-14           0
2           3  Electronics  Brand_70      165.46  2021-01-18           1
3           4      Fashion  Brand_56       75.45  2023-03-03           1
4           5       Sports   Brand_1       72.50  2022-04-19           1

In [19]:
events.head()

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,session_duration_sec,experiment_group
0,1,2021-01-14 13:35:43,43812,535101,view,1004,desktop,Email,43,PLP,115.1,Control
1,2,2021-12-03 21:36:50,71340,96426,add_to_cart,986,desktop,Email,10,PDP,32.4,Variant_A
2,3,2021-12-27 08:25:15,59540,220126,purchase,1630,mobile,Organic,0,PDP,190.7,Variant_A
3,4,2022-01-22 15:06:54,3601,484555,add_to_cart,1532,desktop,Paid Search,30,Checkout,134.8,Variant_B
5,6,2022-03-04 11:41:45,3184,221551,click,628,desktop,Organic,0,PDP,36.8,Variant_A

In [ ]:
customers.head()

,customer_id,signup_date,country,age,gender,loyalty_tier,acquisition_channel
0,1,2021-04-08,BR,48,Male,Bronze,Referral
1,2,2023-04-28,IN,36,Female,Silver,Organic
2,3,2022-12-18,UK,35,Female,Silver,Organic
3,4,2022-04-26,US,45,Male,Silver,Paid Search
4,5,2022-04-20,IN,53,Male,Silver,Organic